# Generated by Django 4.0.5 on 2022-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Creation_time',
            field=models.DateField(verbose_name='CreationTime'),
        ),
    ]
