# Generated by Django 4.0.5 on 2022-06-14 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_job_accepted_developer_job_applied_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_developer',
            field=models.ManyToManyField(null=True, related_name='applied_developer', to=settings.AUTH_USER_MODEL),
        ),
    ]
