# Generated by Django 4.0.5 on 2022-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_applied_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='banner_image',
            field=models.ImageField(default='cat.img', upload_to='media'),
        ),
    ]
