# Generated by Django 4.0.5 on 2022-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_modification_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Modification_time',
            field=models.DateField(blank=True, null=True, verbose_name='Modification Time'),
        ),
    ]
