# Generated by Django 4.0.4 on 2022-06-16 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_remove_job_modification_time_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='banner_image',
            field=models.ImageField(default='job.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
