# Generated by Django 4.0.5 on 2022-06-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_banner_image'),
        ('job', '0007_alter_job_banner_image_alter_job_created_by'),
    ]

    operations = [
    ]
