# Generated by Django 4.0.5 on 2022-06-18 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0009_alter_job_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='accepted_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_developer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='applied_developer',
            field=models.ManyToManyField(blank=True, null=True, related_name='applied_developer', to=settings.AUTH_USER_MODEL),
        ),
    ]
